version: "3.8"
name: "e-commerce"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api/data:/app/data
    env_file:
      - ./api/api.env
    restart: unless-stopped

  order:
    build:
      context: .
      dockerfile: ./order/Dockerfile
    volumes:
      - ./order/data:/app/data
    env_file:
      - ./order/order.env
    restart: unless-stopped

  product:
    build:
      context: .
      dockerfile: ./product/Dockerfile
    volumes:
      - ./product/data:/app/data
    env_file:
      - ./product/product.env
    restart: unless-stopped

  warehouse:
    build:
      context: .
      dockerfile: ./warehouse/Dockerfile
    volumes:
      - ./warehouse/data:/app/data
    env_file:
      - ./warehouse/warehouse.env
    restart: unless-stopped

  shop:
    build:
      context: .
      dockerfile: ./shop/Dockerfile
    volumes:
      - ./shop/data:/app/data
    env_file:
      - ./shop/shop.env
    restart: unless-stopped

  payment:
    build:
      context: .
      dockerfile: ./payment/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./payment/data:/app/data
    env_file:
      - ./payment/payment.env
    restart: unless-stopped
