version: "3.8"
name: "e-commerce"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./api/api.env
    restart: unless-stopped

  order:
    build:
      context: .
      dockerfile: ./order/Dockerfile
    env_file:
      - ./order/order.env
    restart: unless-stopped

  product:
    build:
      context: .
      dockerfile: ./product/Dockerfile
    env_file:
      - ./product/product.env
    restart: unless-stopped

  warehouse:
    build:
      context: .
      dockerfile: ./warehouse/Dockerfile
    env_file:
      - ./warehouse/warehouse.env
    restart: unless-stopped

  shop:
    build:
      context: .
      dockerfile: ./shop/Dockerfile
    env_file:
      - ./shop/shop.env
    restart: unless-stopped
