version: "3.8"
name: "e-commerce"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PRODUCT_SERVICE_ADDR=product:50052
      - WAREHOUSE_SERVICE_ADDR=warehouse:50053
      - SHOP_SERVICE_ADDR=shop:50054
    restart: unless-stopped

  order:
    build:
      context: .
      dockerfile: ./order/Dockerfile
    # ports:
    #   - "50051:50051"
    environment:
      - PRODUCT_SERVICE_ADDR=product:50052
      - WAREHOUSE_SERVICE_ADDR=warehouse:50053
    restart: unless-stopped

  product:
    build:
      context: .
      dockerfile: ./product/Dockerfile
    # ports:
    #   - "50052:50052"
    restart: unless-stopped

  warehouse:
    build:
      context: .
      dockerfile: ./warehouse/Dockerfile
    # ports:
    #   - "50053:50053"
    restart: unless-stopped

  shop:
    build:
      context: .
      dockerfile: ./shop/Dockerfile
    # ports:
    #   - "50054:50054"
    restart: unless-stopped
